### ISSUE TITLE
Non-previous experience with Unity

### ISSUE THREAD

**Issue by yecto** [moxuse/tidal-unity#2]
Hi Mori thanks for this, is amazing, I would like to have a bit more details about where I should create 'Assets / Resources / Things' on my computer?, also, when I evaluate ': load ~ / UnityOsc' - it works, but then 'v1 <- unityStream' - it gives me 'Variable not in scope ', finally I would like to know, to run Unity, I must open' tidal-unity.unity ', right? - xx.

**Comment by moxuse** [comment]
The repositoy has 'scene file' for open that project. You don’t need to make new project.
You can find Assets/tidal-unity.unity file.

**Comment by moxuse** [comment]
It seems problem from timing of declaration of `retrig` function maybe.

https://github.com/tidalcycles/Tidal/blob/master/tidal.el#L167

you may should load module after declaration  of `retrig` function.
